apiVersion: v1
kind: Secret
metadata:
  name: mysql-secret
  namespace: softconsist
type: Opaque
data:
  mysql-root-password: cm9vdA==        # root
  mysql-database: c29mdGNvbnNpc3Q=     # softconsist

