apiVersion: v1
kind: Service
metadata:
  name: softconsist-frontend
  namespace: softconsist
spec:
  type: ClusterIP
  selector:
    app: softconsist-frontend
  ports:
    - port: 80
      targetPort: 80

